# Generated by Django 5.1.6 on 2025-03-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_analysisresult_resume_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
